-- MySQL Script generated by MySQL Workbench
-- Fri Sep 27 07:32:10 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema PlayStation
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `PlayStation` ;

-- -----------------------------------------------------
-- Schema PlayStation
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `PlayStation` DEFAULT CHARACTER SET utf8 ;
USE `PlayStation` ;

-- -----------------------------------------------------
-- Table `PlayStation`.`PlayStation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PlayStation`.`PlayStation` ;

CREATE TABLE IF NOT EXISTS `PlayStation`.`PlayStation` (
  `noSerie` VARCHAR(10) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `paisOrigen` VARCHAR(45) NOT NULL,
  `year` INT NOT NULL,
  PRIMARY KEY (`noSerie`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PlayStation`.`Cuenta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PlayStation`.`Cuenta` ;

CREATE TABLE IF NOT EXISTS `PlayStation`.`Cuenta` (
  `nombreUsuario` VARCHAR(45) NOT NULL,
  `correo` VARCHAR(100) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`nombreUsuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PlayStation`.`PlayStationPlus`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PlayStation`.`PlayStationPlus` ;

CREATE TABLE IF NOT EXISTS `PlayStation`.`PlayStationPlus` (
  `idPlayStationPlus` INT NOT NULL,
  `Cuenta_nombreUsuario` VARCHAR(45) NOT NULL,
  `PlayStation_noSerie` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`idPlayStationPlus`, `Cuenta_nombreUsuario`, `PlayStation_noSerie`),
  INDEX `fk_PlayStationPlus_Cuenta1_idx` (`Cuenta_nombreUsuario` ASC) VISIBLE,
  INDEX `fk_PlayStationPlus_PlayStation1_idx` (`PlayStation_noSerie` ASC) VISIBLE,
  CONSTRAINT `fk_PlayStationPlus_Cuenta1`
    FOREIGN KEY (`Cuenta_nombreUsuario`)
    REFERENCES `PlayStation`.`Cuenta` (`nombreUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PlayStationPlus_PlayStation1`
    FOREIGN KEY (`PlayStation_noSerie`)
    REFERENCES `PlayStation`.`PlayStation` (`noSerie`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PlayStation`.`PlayStation_has_Cuenta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PlayStation`.`PlayStation_has_Cuenta` ;

CREATE TABLE IF NOT EXISTS `PlayStation`.`PlayStation_has_Cuenta` (
  `PlayStation_noSerie` VARCHAR(10) NOT NULL,
  `Cuenta_nombreUsuario` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`PlayStation_noSerie`, `Cuenta_nombreUsuario`),
  INDEX `fk_PlayStation_has_Cuenta_Cuenta1_idx` (`Cuenta_nombreUsuario` ASC) VISIBLE,
  INDEX `fk_PlayStation_has_Cuenta_PlayStation1_idx` (`PlayStation_noSerie` ASC) VISIBLE,
  CONSTRAINT `fk_PlayStation_has_Cuenta_PlayStation1`
    FOREIGN KEY (`PlayStation_noSerie`)
    REFERENCES `PlayStation`.`PlayStation` (`noSerie`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PlayStation_has_Cuenta_Cuenta1`
    FOREIGN KEY (`Cuenta_nombreUsuario`)
    REFERENCES `PlayStation`.`Cuenta` (`nombreUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
